dist: trusty

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: TYPO3=^8.7
    - php: 7.3
      env: TYPO3=^8.7
    - php: 7.2
      env: TYPO3=^8.7
    - php: 7.1
      env: TYPO3=^8.7
    - php: 7.0
      env: TYPO3=^8.7
    - php: 7.2
      env: TYPO3=^7.6
    - php: 7.1
      env: TYPO3=^7.6
    - php: 7.0
      env: TYPO3=^7.6
    - php: 5.6
      env: TYPO3=^7.6
    - php: 5.5
      env: TYPO3=^7.6

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false


before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - >
    if [[ "$TYPO3" = *"dev"* ]]; then
      composer remove thibaud-dauce/mattermost-php --no-update;
    fi
  - composer require typo3/cms="$TYPO3"
  - git checkout composer.json
  - mkdir -p .Build/Web/typo3conf/ext/
  - if [ ! -L .Build/Web/typo3conf/ext/caretaker_mattermost ]; then ln -snvf ../../../../. .Build/Web/typo3conf/ext/caretaker_mattermost; fi
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" ! -path "./Resources/Php/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
